highlighter: pygments
safe: true
lsi: false

exclude: [ '*.sublime*', 'README.md' ]

sass:
    style: :compressed

defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
